/*
 * This file is generated by jOOQ.
 */
package moe.crx.jooq.tables.records;


import moe.crx.jooq.tables.Boards;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BoardsRecord extends UpdatableRecordImpl<BoardsRecord> implements Record7<Long, String, String, String, Boolean, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.boards.id</code>.
     */
    public BoardsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.boards.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.boards.tag</code>.
     */
    public BoardsRecord setTag(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.boards.tag</code>.
     */
    public String getTag() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.boards.name</code>.
     */
    public BoardsRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.boards.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.boards.description</code>.
     */
    public BoardsRecord setDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.boards.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.boards.visible</code>.
     */
    public BoardsRecord setVisible(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.boards.visible</code>.
     */
    public Boolean getVisible() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.boards.locked</code>.
     */
    public BoardsRecord setLocked(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.boards.locked</code>.
     */
    public Boolean getLocked() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.boards.nsfw</code>.
     */
    public BoardsRecord setNsfw(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.boards.nsfw</code>.
     */
    public Boolean getNsfw() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, Boolean, Boolean, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, Boolean, Boolean, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Boards.BOARDS.ID;
    }

    @Override
    public Field<String> field2() {
        return Boards.BOARDS.TAG;
    }

    @Override
    public Field<String> field3() {
        return Boards.BOARDS.NAME;
    }

    @Override
    public Field<String> field4() {
        return Boards.BOARDS.DESCRIPTION;
    }

    @Override
    public Field<Boolean> field5() {
        return Boards.BOARDS.VISIBLE;
    }

    @Override
    public Field<Boolean> field6() {
        return Boards.BOARDS.LOCKED;
    }

    @Override
    public Field<Boolean> field7() {
        return Boards.BOARDS.NSFW;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTag();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public Boolean component5() {
        return getVisible();
    }

    @Override
    public Boolean component6() {
        return getLocked();
    }

    @Override
    public Boolean component7() {
        return getNsfw();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTag();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public Boolean value5() {
        return getVisible();
    }

    @Override
    public Boolean value6() {
        return getLocked();
    }

    @Override
    public Boolean value7() {
        return getNsfw();
    }

    @Override
    public BoardsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BoardsRecord value2(String value) {
        setTag(value);
        return this;
    }

    @Override
    public BoardsRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public BoardsRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public BoardsRecord value5(Boolean value) {
        setVisible(value);
        return this;
    }

    @Override
    public BoardsRecord value6(Boolean value) {
        setLocked(value);
        return this;
    }

    @Override
    public BoardsRecord value7(Boolean value) {
        setNsfw(value);
        return this;
    }

    @Override
    public BoardsRecord values(Long value1, String value2, String value3, String value4, Boolean value5, Boolean value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BoardsRecord
     */
    public BoardsRecord() {
        super(Boards.BOARDS);
    }

    /**
     * Create a detached, initialised BoardsRecord
     */
    public BoardsRecord(Long id, String tag, String name, String description, Boolean visible, Boolean locked, Boolean nsfw) {
        super(Boards.BOARDS);

        setId(id);
        setTag(tag);
        setName(name);
        setDescription(description);
        setVisible(visible);
        setLocked(locked);
        setNsfw(nsfw);
    }

    /**
     * Create a detached, initialised BoardsRecord
     */
    public BoardsRecord(moe.crx.jooq.tables.pojos.Boards value) {
        super(Boards.BOARDS);

        if (value != null) {
            setId(value.getId());
            setTag(value.getTag());
            setName(value.getName());
            setDescription(value.getDescription());
            setVisible(value.getVisible());
            setLocked(value.getLocked());
            setNsfw(value.getNsfw());
        }
    }
}
