/*
 * This file is generated by jOOQ.
 */
package moe.crx.jooq;


import moe.crx.jooq.tables.Boards;
import moe.crx.jooq.tables.Categories;
import moe.crx.jooq.tables.Images;
import moe.crx.jooq.tables.Posts;
import moe.crx.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.boards</code>.
     */
    public static final Boards BOARDS = Boards.BOARDS;

    /**
     * The table <code>public.categories</code>.
     */
    public static final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>public.images</code>.
     */
    public static final Images IMAGES = Images.IMAGES;

    /**
     * The table <code>public.posts</code>.
     */
    public static final Posts POSTS = Posts.POSTS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
