/*
 * This file is generated by jOOQ.
 */
package moe.crx.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import moe.crx.jooq.Keys;
import moe.crx.jooq.Public;
import moe.crx.jooq.tables.records.BoardsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function9;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Boards extends TableImpl<BoardsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.boards</code>
     */
    public static final Boards BOARDS = new Boards();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BoardsRecord> getRecordType() {
        return BoardsRecord.class;
    }

    /**
     * The column <code>public.boards.id</code>.
     */
    public final TableField<BoardsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.boards.tag</code>.
     */
    public final TableField<BoardsRecord, String> TAG = createField(DSL.name("tag"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.boards.name</code>.
     */
    public final TableField<BoardsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.boards.description</code>.
     */
    public final TableField<BoardsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.boards.visible</code>.
     */
    public final TableField<BoardsRecord, Boolean> VISIBLE = createField(DSL.name("visible"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.boards.locked</code>.
     */
    public final TableField<BoardsRecord, Boolean> LOCKED = createField(DSL.name("locked"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.boards.nsfw</code>.
     */
    public final TableField<BoardsRecord, Boolean> NSFW = createField(DSL.name("nsfw"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.boards.headerImage</code>.
     */
    public final TableField<BoardsRecord, Long> HEADERIMAGE = createField(DSL.name("headerImage"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.boards.parentCategory</code>.
     */
    public final TableField<BoardsRecord, Long> PARENTCATEGORY = createField(DSL.name("parentCategory"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("0", SQLDataType.BIGINT)), this, "");

    private Boards(Name alias, Table<BoardsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Boards(Name alias, Table<BoardsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.boards</code> table reference
     */
    public Boards(String alias) {
        this(DSL.name(alias), BOARDS);
    }

    /**
     * Create an aliased <code>public.boards</code> table reference
     */
    public Boards(Name alias) {
        this(alias, BOARDS);
    }

    /**
     * Create a <code>public.boards</code> table reference
     */
    public Boards() {
        this(DSL.name("boards"), null);
    }

    public <O extends Record> Boards(Table<O> child, ForeignKey<O, BoardsRecord> key) {
        super(child, key, BOARDS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<BoardsRecord, Long> getIdentity() {
        return (Identity<BoardsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<BoardsRecord> getPrimaryKey() {
        return Keys.BOARDS_PK;
    }

    @Override
    public List<UniqueKey<BoardsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.BOARDS_TAG_KEY);
    }

    @Override
    public Boards as(String alias) {
        return new Boards(DSL.name(alias), this);
    }

    @Override
    public Boards as(Name alias) {
        return new Boards(alias, this);
    }

    @Override
    public Boards as(Table<?> alias) {
        return new Boards(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Boards rename(String name) {
        return new Boards(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Boards rename(Name name) {
        return new Boards(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Boards rename(Table<?> name) {
        return new Boards(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, Boolean, Boolean, Boolean, Long, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function9<? super Long, ? super String, ? super String, ? super String, ? super Boolean, ? super Boolean, ? super Boolean, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function9<? super Long, ? super String, ? super String, ? super String, ? super Boolean, ? super Boolean, ? super Boolean, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
